language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
after_script:
- greenkeeper-lockfile-upload
- npm run coverage
- codecov
env:
  global:
    secure: ZaJBay+Yk4558jO3e/ibOFij4B52fznDn8aARakf1zETya5chCoSftrOcqDL3gJnU9DozMs+8QWeNGHLpu/kCBaiMU2sErCBidoYYK6hBlAyZHKBdSewebz5ix5GTjoEKFk6JSId9FCy2V/JTBlLWM6NXjQqeAhwg78jh0LFBNq+/QtgHopXuzjA6q4y/VAr0Z5DfWX4p39xQyhLguG2AO8BYDIJkEo+cOlF76SkA4p63cd9uAdRtgwBTykCrEuMv82AgrGzBxmGlTR0ZjIgGJvbuQdEdz2rVbBuMYUJsIuGvVFyI35YRcxukP2E/rCGIiERTkqohVBhZY40RA/zFq8OUWA30yj/K3DQjbVzDMjMXCKfm2ddzpmuI0MGl4dwAAwEiR9KnvKsyBqBwVaU3U4VD0x/4CH5EH05dLs/gMoyM6QJl520rWv9ilgLZ75FHFh4VbuGrmJ98V247b3T45xiVUGb/qt5gPRx0vHdV0eFWWmTbCuVRvrSjp8fETiCz7Z0PaDNrMdqxdhKH4D1UzbAAHrJLTHO3y8mNJrlFMBGkUyfB/7ihrac3020z9HAzco2VnrbYNL7CXbEX8Ea3dH6d4SD5xzVvDh+QfDn4hvn1w29bj64bW/fTf3QZUiyrkKtAaHReQCTfpjCAs/T+O0Q/btabHJ3nk6HwYFx1bQ=
